### ISSUE TITLE
[PetLives] Task #600 for PetLives v1.2.1 generated an exception

### ISSUE THREAD

**Issue by vandon1** [hyperdefined/PetLives#18]
Petlives 1.2.1 seems to fill the console with exceptions when players add lives, kill a pet, or try to check lives on a pet. It also produces a single exception on startup.
I have tried removing all the old datafiles in the plugin config directory and starting fresh. New config and no player/pet files and it still gives the exceptions. 
Pet lives, killing a pet/taking a life seem to work ok. Checking a pet or using a UUID to check returns nothing to the player. All the commands produce an exception whether they work or not.

[22:09:37] [Server thread/INFO]: This server is running Paper version git-Paper-446 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4e99466)

[22:10:04] [Server thread/WARN]: [PetLives] Task #600 for PetLives v1.2.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.AnimalTamer.getUniqueId()" because the return value of "org.bukkit.entity.Tameable.getOwner()" is null
	at lol.hyper.petlives.events.ChunkLoad.lambda$onChunkLoad$0(ChunkLoad.java:46) ~[petlives-1.2.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-446]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-446]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-446]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by hyperdefined** [comment]
That is a strange error... all that error is saying is that the entity does not have an owner even if it's tamed. As for other things not working, that's even more stranger. I test v1.2.1 on Paper 446, and do not have these issues. Could you provide more logs of various different errors? This might be a bit hard to debug.

**Comment by vandon1** [comment]
So after testing more, I put the updated version on my creative server that run the same plugins and I don't get the exceptions. I'm guessing that one of the animals somewhere has some odd nbt data or something.

**Comment by hyperdefined** [comment]
I'm a bit confused, as 1.2.1 is the latest version, so not sure what "updated version" you meant. Regardless, glad it works now.

**Comment by vandon1** [comment]
> I'm a bit confused, as 1.2.1 is the latest version, so not sure what "updated version" you meant. Regardless, glad it works now.

My creative server was still running 1.2, not 1.2.1. I updated it to 1.2.1
